version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    env_file:
    - .env
    image: postgres:16.0-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    build: .
    volumes:
      - ./app:/code/app
    command:  uvicorn app.main:app --host 0.0.0.0 --reload --port ${BACKEND_PORT}
    restart: on-failure
    depends_on: 
      - postgres

volumes:
  pgdata: